language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

stages:
  - lint
  - test
  - name: deploy
    if: tag IS present
jobs:
  include:
    - stage: lint
      script: tslint 'src/**/*.ts'

    # For test for now just make sure we can build it I guess
    - stage: test
      script: npm run build

    # Deploy the thing to Chrome Web Store automatically
    - stage: deploy
      script: bash deploy.sh

# Turn off email notifs
notifications:
  email: false
