# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Chrome

on:
  push:
    branches:
      - master
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build

    - name: Remove the firefox only keys from the manifest for chrome
      run: node chromify.js

    - name: Create the Chrome zip
      working-directory: dist
      run: zip -r ../dist.zip *

    - name: Upload to Chrome
      uses:  Passiverecords/chrome-extension-upload-action@1.4.1
      with:
        refresh-token: '${{ secrets.REFRESH_TOKEN }}'
        client-id: '${{ secrets.CLIENT_ID }}'
        client-secret: '${{ secrets.CLIENT_SECRET }}'
        file-name: './dist.zip'
        app-id: 'kikdmnikeponomghepmfipgiijlmfhfl'
        publish: true
